### ISSUE TITLE
Terms & Agreements

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#135]
AC:
- [x] Add [Terms of Use](https://xd.adobe.com/view/efd9e193-b8b1-4fc7-9649-e362a7c6c43c-ba8a/) landing page.

@KostiaLevchenko dis naming and content

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamDevilsTeam-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/135?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
[https://app.zenhub.com/files/492804248/04e3b693-0c7f-430e-9567-71b8c27f7a27/download](https://app.zenhub.com/files/492804248/04e3b693-0c7f-430e-9567-71b8c27f7a27/download)
