### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#195]
AC:
- [x] Apply new designs on the **Contact Us Form** page.

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/12b29b0c-971f-491c-b266-74484819b06b)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamutyBoard-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/195?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
[contact.txt](https://github.com/Cam-Devils/CamDevilsZen/files/8891207/contact.txt)
