### ISSUE TITLE
DMCA page/form

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#197]
AC:
- [x] Apply new designs on the DMCA page.

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/d0aa3787-ede5-4389-a3bb-ac4b91cb5482)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamutyBoard-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/197?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
[about.txt](https://github.com/Cam-Devils/CamDevilsZen/files/8891193/about.txt)

**Comment by SDezineUK** [comment]
[dmca.txt](https://github.com/Cam-Devils/CamDevilsZen/files/8891198/dmca.txt)
