### ISSUE TITLE
Term & Agreements Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#198]
AC: 
- [x] Apply new designs on the **Term & Agreements**  page.
- [x] Use schema colors for titles.

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/7c8756fa-49e9-4502-bf34-6b39c7496ea8)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamutyBoard-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/198?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
[tos.txt](https://github.com/Cam-Devils/CamDevilsZen/files/8891185/tos.txt)
