### ISSUE TITLE
About us Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#199]
)AC: 
- [x] Apply new designs on the **About us** page.
**Notes:** 
- Use thinner paragraph separator lines. 
- Use site color scheme color instead of a gradient for lines 
- Don't add **Services and benefits** paragraph

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/4db52347-dc8c-4eb0-8c5b-2883a3006f1f)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamutyBoard-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/199?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
[about.txt](https://github.com/Cam-Devils/CamDevilsZen/files/8891201/about.txt)
