### ISSUE TITLE
Styles for See More/All buttons and pagination

### ISSUE THREAD

**Issue by bcmp4p1** [Cam-Devils/CamDevilsZen#219]
AC:
- [ ] Add styles for button See More
- [ ] Add styles for button See All
- [ ] Remove See All (if models.length < 12) on the search page
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/3d7e961f-6415-40b6-8842-e5e1155b55b4)
- [ ] Add new styles for pagination
![image.png](https://images.zenhubusercontent.com/6270ce45b18ff5e9f59b2c12/c5764135-ae19-46e4-ab76-356ca17005b4)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CamutyBoard-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/219?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
