### ISSUE TITLE
Home page: custom selection

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#221]
AC: 
- [x] Adjust frontend to accept new response type from backend for `GET`: `/api/performer`

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/221?planning-poker) with ZenHub @bcmp4p1 @aleksandra-mileant
