### ISSUE TITLE
See All button

### ISSUE THREAD

**Issue by bcmp4p1** [Cam-Devils/CamDevilsZen#234]
AC:
- [ ] Hide See All button for a category of number of performers less than 24 

**Note:** Display separate line instead of button SeeAll when performers count <= 24

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/234?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
