### ISSUE TITLE
Footer: naming&redirects

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#245]
AC:
- [x] Remove the **Work with us** column.
- [x] Rename **Billing support** to **About us**
- [x] Remove **Terms of use**.
- [x] Rename **Privacy Policy** to **DMCA** and add a redirect to **DMCA** landing page.
- [x] Add container to the footer to make the footer looks consistent on different screen sizes.
- [x] Change select area for logo.

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/0653df34-56a5-4b79-a15c-5408d8228b8c)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/245?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
Columns should be like this:
1. Legal & Safety: Privacy Policy, Terms of Use, DMCA Policy, Cookies Policy
2. Help & Support: Contact & Support, Billing Support
3. Camutik: About Camutik, Blog, Twitter, Instagram, Youtube, Reddit

The footer still isn't spaced out very well. I like the spacing in the footer here:
https://sharpedezine.com/cam-project/design/
