### ISSUE TITLE
Ukraine To Models

### ISSUE THREAD

**Issue by SDezineUK** [Cam-Devils/CamDevilsZen#246]
AC:

Problem: When a user clicks this link, we currently take them to a page that has the "see more" and "see all". They have actively chosen to see these models so I think it is better if this page shows all the models with pagination, instead.
- [ ] Fix: Ukraine To Models page.
- [ ] Add flag to name.

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/246?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
