### ISSUE TITLE
Tags should have a space on model's page

### ISSUE THREAD

**Issue by rymdapaz** [Cam-Devils/CamDevilsZen#247]
Steps to reproduce:
1. Open home page 
2. Choose any model on home screen 
3. On model's page take a look on a "Tags" block 

Actual result: Tags have no space between them 

Expected result: Tags should have a space on model's page 

![Снимок экрана 2022-06-22 в 16.33.24.png](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/669c1d38-7d32-41b6-9a71-055b518ee98c)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/247?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
