### ISSUE TITLE
The sidebar goes under the footer, when scrolling down on a "Filters" page

### ISSUE THREAD

**Issue by rymdapaz** [Cam-Devils/CamDevilsZen#248]
Steps to reproduce:
1. Open the home page
2. Click "Show all tags" on the sidebar 
3. Scroll down on a "Filters" page 

Actual result: The sidebar goes under the footer, when scrolling down
![Peek 2022-06-22 23-51.gif](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/6c3c874a-c7a9-41d9-b481-f4b372200161)
Expected result: Sidebar options should be visible after scrolling down

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/248?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
