### ISSUE TITLE
Search bar styling and UX

### ISSUE THREAD

**Issue by SDezineUK** [Cam-Devils/CamDevilsZen#253]
AC:
Please match the styling of the search bar to what we have in the Figma file. 
- [x] Reduce the size of the search icon and move it to the left
- [x] Emphasize the clear icon and also make it a little bit smaller

In the dropdown menu
- [x] Fix the fonts used here
- [x] Make the gender tabs look better
- [x] Remove the pink from the scrollbar (make it the same color we discussed with @aleksandra-mileant )
- [x] Fix the scrollbar so it doesn't look like it is outside the container.

**Comment by SDezineUK** [comment]
Example of how the tabs in the dropdown could look. We will use only icon ![dropdown-tabs.png](https://images.zenhubusercontent.com/627149f8b18ff5f3c6a11335/20533f4a-98c8-4530-be9e-c0370c8aa192)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/253?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1
