### ISSUE TITLE
DMCA page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#263]
AC: 
- [x] Put everything in containers to make look consistent on different screens
- [x] Change the style of Send From button to ![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/f10320ad-2475-420e-acbb-0e50840a92f5)

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/1571962c-6775-4430-bea0-04bf2a9ca9dc)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/263?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by rymdapaz** [comment]
The button style has not changed.
![Снимок экрана 2022-07-07 в 11.06.41.png](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/265139e0-99d4-4e33-b3df-3ec5199ff720)


On mobile device - iphone 12 
Placeholder in "Submitted On" form is not displayed on mobile device 
![IMG_2561.jpg](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/c4ec38ea-871d-47ee-95ec-4ea57639ca0a)
