### ISSUE TITLE
Terms and agreements

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#264]
AC:
- [x] Put everything in containers to make look consistent on different screens.
- [x] Use only **white** for text (no colors)
- [x] Add **white** separation lines between paragraphs.

![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/d1c9e164-cb49-47ff-82fc-0670254800af)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/264?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by rymdapaz** [comment]
Some paragraphs have a large space between words - iphone 12

![IMG_2559.jpg](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/a4bb6de8-23f2-4c5d-9765-ca4058fe84a6)

![IMG_2558.jpg](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/31009969-d426-48e3-8f81-396bb0c21792)

![IMG_2557.jpg](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/80f9c9f7-a903-44bf-84fc-2657b1a7108b)

![IMG_2556.jpg](https://images.zenhubusercontent.com/62b2eee3c32d1bfdf0f2d6d7/1730c424-a4cf-4700-87e4-bdce2d81bc12)
