### ISSUE TITLE
Error on Filter Submit

### ISSUE THREAD

**Issue by SDezineUK** [Cam-Devils/CamDevilsZen#321]

**Comment by SDezineUK** [comment]
Submitting here takes you to the show all tags page.
Also, the text on that button should be "Show Results" I think.
![image.png](https://images.zenhubusercontent.com/627149f8b18ff5f3c6a11335/5951837f-0673-4ad9-a9e7-4471dd6d4cf1)

**Comment by KostiaLevchenko** [comment]
Resolved in https://app.zenhub.com/workspaces/camutick-628234c52c002e0018e320ec/issues/cam-devils/camdevilszen/346
