### ISSUE TITLE
Sitemap xml

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#348]
AC:
- [ ] Create Sitemap.xml file in the root directory.
- [ ] Map available URLs on Sitemap.xml

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/348?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
Please note that we don't want to map performer pages. We want to map our main pages and our filter pages.
Here's stripchat's sitemap file: https://stripchat.com/sitemap.xml for an example.
