### ISSUE TITLE
About us: Platforms we work with 

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#350]
AC:
- [x] Add a list of Affiliate platforms.
- [x] Add functionality to redirect on click.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/3c6126e1-5abb-4f21-a0f6-31e60df2499a)

**Comment by KostiaLevchenko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/350?planning-poker) with ZenHub @aleksandra-mileant @bcmp4p1

**Comment by SDezineUK** [comment]
Some partners have provided their logos in svg. A couple have not.
[https://app.zenhub.com/files/492804248/3ffaf13e-d4cf-4ec7-ac49-25f1c1b11be4/download](https://app.zenhub.com/files/492804248/3ffaf13e-d4cf-4ec7-ac49-25f1c1b11be4/download)
