### ISSUE TITLE
Billing support 

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#390]
AC:
- [x] Remove Billing support from the footer. 
- [x] Add the `Billing support` button next to 'See our DMCA` button. 
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/efff8983-98b9-4c29-b5ab-31e8bfc4f5c5)
- [x] Onclick `Billing support` opens the dialog window with a text message.
https://mui.com/material-ui/react-dialog/

**Comment by SDezineUK** [comment]
The text in the dialog will read as follows:

Camutik is a cam aggregation app and does not undertake any billing operations. If you have a query about billing, please get in touch with billing support for the relevant platform.
