### ISSUE TITLE
DMCA form update

### ISSUE THREAD

**Issue by bcmp4p1** [Cam-Devils/CamDevilsZen#449]
- [ ] delete field '*Submitted On'
- [ ] add Date.now to submitted form

**Comment by SDezineUK** [comment]
For the data and subject, can you add them to the form as hidden fields, please. For example:
```
<input type="hidden" name="Subject" value="username DMCA Notice - Camutik">
<input type="hidden" name="submitted" value="08 August, 2022">
```
Similar for the contact page subject:
```<input type="hidden" name="Subject" value="Contact - Camutik">```
