### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by SDezineUK** [Cam-Devils/CamDevilsZen#460]
AC:
- [ ] Please add the following codes to the site:

Add the following code just before the </head> tag:
```<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />```

Add the following code just before the </body> tag:
```<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#252b2d",
      "text": "#d9d9d9"
    },
    "button": {
      "background": "#de5e9d",
      "text": "#ffffff"
    }
  },
  "theme": "edgeless",
  "position": "bottom-left",
  "content": {
    "href": "https://www.iubenda.com/privacy-policy/28654806/cookie-policy"
  }
});
</script>```

**Comment by SDezineUK** [comment]
Please add the following codes to the site:

Add the following code just before the </head> tag:
```<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />```

Add the following code just before the </body> tag:
```<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#252b2d",
      "text": "#d9d9d9"
    },
    "button": {
      "background": "#de5e9d",
      "text": "#ffffff"
    }
  },
  "theme": "edgeless",
  "position": "bottom-left",
  "content": {
    "href": "https://www.iubenda.com/privacy-policy/28654806/cookie-policy"
  }
});
</script>```

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/460?planning-poker) with ZenHub @bcmp4p1 @aleksandra-mileant

**Comment by SDezineUK** [comment]
Seems some of my text got removed from this. The second part of this code (the script part) should go just before the closing body tag.
