### ISSUE TITLE
Fix Sirportly forms

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#462]
AC:
- [x] Add auth key to request for Sirportly endpoints.

**Comment by SDezineUK** [comment]
DMCA Form:
- "URL of work being infringed" (infringed is spelled incorrectly)
- "Copyright Ownership" should be "Your Platform"
- We need a space for an electronic signature
- UNDER PENALTY OF PERJURY, I am the owner or agent authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
- By completing the DMCA Form and reading the DMCA Policy I agree that all the information above is real and if not I am aware that legal action will be taken. (remove this line)

Contact Form:
- Change "Full Name" to just "Name"
- Change "Description of work being infringed" to "Your Message"
- By completing this form I agree to your Terms and Agreements and I agree that the information I submit above is real, if not I am aware that legal action will be taken. (remove this line)
- By submitting this form I agree to the <a href="">Terms of use</a> and <a href="">Privacy Policy</a> (add this line)
