### ISSUE TITLE
Performer platform id

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#466]
Performer platform id#465
AC:

 Add platform id to get performer endpoint.

`GET`: `/api/performer/PERFROMER_NAME/?user_country=UA&partner=PARTNER_ID`

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/466?planning-poker) with ZenHub @bcmp4p1 @aleksandra-mileant
