### ISSUE TITLE
Show if the performer offline 

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#467]
AC:
- [ ] Check performer status if online show Image instead of iframe.

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Camutick-628234c52c002e0018e320ec/issues/Cam-Devils/CamDevilsZen/467?planning-poker) with ZenHub @bcmp4p1 @aleksandra-mileant
