### ISSUE TITLE
Footer social networks list

### ISSUE THREAD

**Issue by KostiaLevchenko** [Cam-Devils/CamDevilsZen#67]
AC:
- [ ] Provide a list of social network links that will be displayed in the footer. 
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/d2404076-6942-418c-8660-ac4cb9a49701)

**Comment by SDezineUK** [comment]
We will use: Twitter, Instagram, Reddit, and Youtube. I will provide links to them once I have a domain name secured.
